location /healthcheck {
    add_header Content-Type text/plain;
    return 200 "OK Computer!";
}

location / {
    proxy_pass $rpi_effinmoney_www$uri$is_args$args;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
}